### ISSUE TITLE
Modifying state during view update

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/swiftui-dsl#55]
There appears to be an issue with modifying state during view update in one code path. The issue is that `parent.camera` is a `@Binding`, so we're mutating state up the chain.

In years past, I would have just reached for `dispatch_async`, even though it feels a bit dirty. [This guy who claims to work at Apple](https://stackoverflow.com/a/68338358) also seems to agree that it's an acceptable solution as of 2021, but Swift 6 is still trying to figure out a new concurrency story which may complicate things. Does anyone have a better idea?

<img width="3120" alt="image" src="https://github.com/user-attachments/assets/4851211e-c710-44ec-9050-2fd691942606">

**Comment by Archdoog** [comment]
Looking at MapKit. Pretty much every type is wrapped in `@MainActor @preconcurrency`, including their Map view, annotations, etc. Given this library is also just UI, a solution like that seems to make sense here as well. Anything you can think of that needs to be allowed to run on another thread?

**Comment by ianthetechie** [comment]
I'm not sure that actually helps here.

* The function is already `@MainActor`
* `@preconcurrency` is just a band-aid that, in my understanding, just suppresses warnings; it doesn't actually change or fix how your code executes; just says "I know what I'm doing with this pre-Swift 6 code."
* The fundamental problem isn't that the code is running on the wrong thread. It's that it's not allowed to mutate state *at this instant* (during a SwiftUI View update).

This doesn't happen very often, so I think I'm fine with the async dispatch.
